version: "3.4"
services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "${PORT:-5000}:5000"
    environment:
      NODE_ENV: ${NODE_ENV:-production}
    volumes:
      - ./uploads:/usr/src/app/uploads
      - ./logs:/usr/src/app/logs
    env_file:
      - .env.production
